[tool.poetry]
name = "taswira"
version = "0.1.0"
description = "Visualization tool for GCBM output"
authors = ["Abhineet Tamrakar <abhineet97@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
