# This workflow will install Conda environment, run tests and lint with a single version of Python.

name: Continuous Integration

on:
  push:
    branches: [ gh-test ]


jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
      
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7
        mamba-version: "*"
        channels: conda-forge
        channel-priority: true
        activate-environment: taswira
        
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: /usr/local/miniconda/envs/taswira
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
      id: envcache
        
    - name: Update Conda Environment
      run: mamba env update -n taswira -f environment.yml
      
    - name: Install Python package
      shell: bash
      run: |
        conda activate taswira
        python -m pip install -e .
      
    - name: Test
      shell: bash
      run: |
        conda activate taswira
        python -m pytest
