# This workflow will install Conda environment, run tests and lint with a single version of Python.

name: Continuous Integration

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint using pylint
      run: docker build . --target lint
    - name: Test using pytest
      run: docker build . --target unit-test
