# This workflow will install Conda environment, run tests and lint with a single version of Python.

name: Continuous Integration

on:
  push:
    branches: [ gh-test ]


jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
      
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7
        mamba-version: "*"
        channels: conda-forge
        channel-priority: true
        
    - name: Update Conda Environment
      run: mamba env create -f environment.yml
      
    - name: Install Python package
      run: |
        conda activate taswira
        python -m pip install -e .
      
    - name: Test
      run: |
        python -m pytest
